variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test
  - build

test:
  stage: test
  image: golang:1.18.1-buster
  script:
    - go test ./...

build:
  stage: build
  image: docker:19.03.13
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  services:
    - docker:19.03.13-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker version
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CONTAINER_TEST_IMAGE -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE