before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "johnuopini/mooncli:{{ .Tag }}"
      - "johnuopini/mooncli:latest"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
